export const GET_ALL_USERS = "GET_ALL_USERS";
export const CREATE_NEW_USERS = "CREATE_NEW_USER";
export const UPDATE_USER = "UPDATE_USER";
export const GET_ALL_TODOS = "GET_ALL_TODOS";
export const GET_ALL_ALBUM = "GET_ALL_ALBUM";
export const GET_ALL_MOVIE = "GET_ALL_MOVIE";
export const GET_ALL_DETAIL = "GET_ALL_DETAIL";
export const API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4MjkxZjI2YmYwN2U5MTExODE1MTY3NDUyMWUyOTcwNCIsInN1YiI6IjYzMzQ1NzEzMGU2NGFmMDA4NDA2YjdhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wMhXifDMntJ4_kpQdiKH2zEoIyiBxt3Q0s0VQEFz3SE";
